const $ = (s, root=document) => root.querySelector(s);
const state = {category:'Tout',query:'',selected:{},checked:{},active:null,variant:'',scale:1,plan:null};
try {
  const saved = JSON.parse(localStorage.getItem('cuisine-mouvement-v1'));
  if (saved && typeof saved === 'object') {
    state.selected = saved.selected && typeof saved.selected === 'object' ? saved.selected : {};
    state.checked = saved.checked && typeof saved.checked === 'object' ? saved.checked : {};
    state.plan = saved.plan && typeof saved.plan === 'object' ? saved.plan : null;
  }
} catch (_) {}
const save = () => { try { localStorage.setItem('cuisine-mouvement-v1',JSON.stringify({selected:state.selected,checked:state.checked,plan:state.plan})); } catch (_) {} };
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = n => new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(Math.round((n+Number.EPSILON)*10)/10);
const quantity = (n,u) => `${fmt(n)} ${u}`;
const norm = s => s.toLocaleLowerCase('fr').normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[’']/g,"'").trim();
const unitKey = u => ({'pièces':'pièce','gousses':'gousse','carrés':'carré','tranches':'tranche','sachets':'sachet','boîtes':'boîte','feuilles':'feuille','branches':'branche'}[u] || u);
const unitLabel = (n,u) => n>1 && u==='portion' ? 'portions' : u;
const cleanCount = n => Math.min(30,Math.max(1,Math.round(Number(n)||1)));
// Ingrédients : un tableau [nom, quantité, unité] ; une simple chaîne = sous-titre (« Pour la sauce »)
const isIng = i => Array.isArray(i);
// Une clé = id de recette, éventuellement suivie de « ~variante » (ex. « burger-smash~wrap »)
function resolve(key){const [id,v]=String(key).split('~');const r=recipes.find(x=>x.id===id);if(!r)return null;const va=v?(r.variants||[]).find(x=>x.key===v):null;if(v&&!va)return null;return {key:String(key),r,icon:r.icon,name:va?`${r.name} (${va.label.toLowerCase()})`:r.name,ingredients:va?r.ingredients.map(i=>isIng(i)&&va.swap&&va.swap[i[0]]||i):r.ingredients,steps:va&&va.steps||r.steps}}
const activeKey = () => state.active+(state.variant?'~'+state.variant:'');
function alertToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('visible');clearTimeout(alertToast.timer);alertToast.timer=setTimeout(()=>el.classList.remove('visible'),2300)}
function renderFilters(){const cats=['Tout',...new Set(recipes.map(r=>r.category))];$('#filters').innerHTML=cats.map(c=>`<button type="button" class="filter ${c===state.category?'active':''}" data-filter="${esc(c)}" aria-pressed="${c===state.category}">${esc(c)}</button>`).join('')}
function renderCards(){const q=norm(state.query);const found=recipes.filter(r=>(state.category==='Tout'||r.category===state.category)&&(!q||norm([r.name,r.category,...r.ingredients.filter(isIng).map(i=>i[0]),...(r.variants||[]).map(v=>v.label)].join(' ')).includes(q)));$('#result-count').textContent=`${found.length} recette${found.length>1?'s':''}`;$('#cards').innerHTML=found.map(r=>`<article class="card"><div class="card-top"><span class="card-icon" aria-hidden="true">${r.icon}</span><span class="tag">${esc(r.category)}</span></div><h3>${esc(r.name)}</h3><p class="meta">${r.prep+r.cook} min · ${r.yield} ${esc(r.unit)}${r.macros?` · ${r.macros.kcal} kcal / ${esc(r.macros.per)}`:''}${r.variants?` · ${r.variants.length+1} versions`:''}</p><button class="card-open" type="button" data-open="${r.id}"><span>Voir la recette</span><span aria-hidden="true">↗</span></button></article>`).join('')||'<p class="empty">Aucune recette trouvée.</p>'}
function renderDialog(){const v=resolve(activeKey());if(!v)return;const r=v.r;const multiplier=state.scale/r.yield;const m=r.macros;$('#recipe-content').innerHTML=`<div class="dialog-icon" aria-hidden="true">${r.icon}</div><span class="eyebrow">${esc(r.category.toUpperCase())}</span><h2>${esc(r.name)}</h2>${r.desc?`<p class="dialog-desc">${esc(r.desc)}</p>`:''}<p class="dialog-meta">Préparation ${r.prep} min · Cuisson ${r.cook} min${r.temp?' · Four '+r.temp+' °C':''} · ${esc(r.tools)}</p>${r.variants?`<div class="variants" role="group" aria-label="Version">${[{key:'',label:r.baseVariant||'Classique'},...r.variants].map(x=>`<button type="button" class="filter ${x.key===state.variant?'active':''}" data-variant="${x.key}" aria-pressed="${x.key===state.variant}">${esc(x.label)}</button>`).join('')}</div>`:''}${m?`<div class="macros"><span>Pour ${esc(m.per)}</span><strong>${m.kcal} kcal</strong><span>${m.p} g protéines</span><span>${m.c} g glucides</span><span>${m.f} g lipides</span>${m.note?`<small>${esc(m.note)}</small>`:''}</div>`:''}<div class="scale"><span>Quantité</span><button data-scale="-1" type="button" aria-label="Réduire la quantité">−</button><strong>${state.scale}</strong><button data-scale="1" type="button" aria-label="Augmenter la quantité">+</button><span>${esc(unitLabel(state.scale,r.unit))}${r.portion?' · '+esc(r.portionLabel||'collation')+' : '+esc(r.portion):''}</span></div><h3>Ingrédients</h3><ul class="ingredients">${v.ingredients.map(i=>isIng(i)?`<li><span>${esc(i[0])}</span><strong>${esc(quantity(i[1]*multiplier,i[2]))}</strong></li>`:`<li class="ing-head">${esc(i)}</li>`).join('')}</ul><h3>Préparation</h3><ol class="steps">${v.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p class="note"><strong>Conservation :</strong> ${esc(r.keep)}${r.note?'<br><strong>À savoir :</strong> '+esc(r.note):''}</p><button class="add" type="button" id="add-recipe">Ajouter les ingrédients à ma liste →</button>`}
function openRecipe(id){const r=recipes.find(x=>x.id===id);if(!r)return;state.active=id;state.variant='';state.scale=r.yield;renderDialog();$('#recipe-dialog').showModal()}
function shoppingData(){const map=new Map;for(const [id,batches] of Object.entries(state.selected)){const v=resolve(id);if(!v||!Number.isFinite(+batches)||+batches<=0)continue;for(const i of v.ingredients){if(!isIng(i))continue;const [name,n,unit]=i;const key=norm(name)+'|'+unitKey(unit);const cur=map.get(key);if(cur)cur.qty+=n*(+batches);else map.set(key,{key,name,qty:n*(+batches),unit:unitKey(unit)})}}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
function renderShopping(){const items=shoppingData();$('#cart-count').textContent=items.length;$('#shopping-status').textContent=items.length?`${items.filter(i=>!state.checked[i.key]).length} article(s) à acheter · ${items.length} au total`:'Aucun article';$('#shopping-list').innerHTML=items.map((it,i)=>`<div class="item ${state.checked[it.key]?'done':''}"><input type="checkbox" data-check="${i}" id="item-${i}" ${state.checked[it.key]?'checked':''}><label for="item-${i}">${esc(it.name)}</label><span class="item-qty">${esc(quantity(it.qty,it.unit))}</span></div>`).join('')||'<p class="empty">Ta liste est vide. Ouvre une recette puis ajoute ses ingrédients ici.</p>';const sel=Object.entries(state.selected).filter(([id,n])=>n>0&&resolve(id));if(sel.length){$('#shopping-list').insertAdjacentHTML('beforeend',`<div class="selected"><h3>Recettes ajoutées</h3>${sel.map(([id,n])=>{const v=resolve(id);return `<div class="selected-row"><span>${esc(v.name)} × ${n} fournée${n>1?'s':''}</span><button type="button" data-remove="${esc(id)}" aria-label="Retirer une fournée de ${esc(v.name)}">Retirer une fournée</button></div>`}).join('')}</div>`)}return items}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.category=b.dataset.filter;renderFilters();renderCards()});$('#search').addEventListener('input',e=>{state.query=e.target.value;renderCards()});$('#cards').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openRecipe(b.dataset.open)});$('#close-dialog').addEventListener('click',()=>$('#recipe-dialog').close());$('#recipe-dialog').addEventListener('click',e=>{if(e.target.id==='recipe-dialog')e.target.close();const variant=e.target.closest('[data-variant]');if(variant){state.variant=variant.dataset.variant;renderDialog()}const scale=e.target.closest('[data-scale]');if(scale){state.scale=cleanCount(state.scale+Number(scale.dataset.scale));renderDialog()}if(e.target.id==='add-recipe'){const r=recipes.find(x=>x.id===state.active),key=activeKey();state.selected[key]=(Number(state.selected[key])||0)+state.scale/r.yield;state.selected[key]=Math.round(state.selected[key]*100)/100;save();renderShopping();$('#recipe-dialog').close();alertToast('Ingrédients ajoutés à la liste')}});$('#shopping-list').addEventListener('change',e=>{if(!e.target.matches('[data-check]'))return;const it=shoppingData()[+e.target.dataset.check];if(!it)return;state.checked[it.key]=e.target.checked;save();renderShopping()});$('#shopping-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;state.selected[b.dataset.remove]=Math.max(0,Math.round((Number(state.selected[b.dataset.remove])-1)*100)/100);if(!state.selected[b.dataset.remove])delete state.selected[b.dataset.remove];save();renderShopping()});$('#clear').addEventListener('click',()=>{if(!Object.keys(state.selected).length)return;if(!confirm('Vider toute la liste de courses ?'))return;state.selected={};state.checked={};save();renderShopping()});$('#copy').addEventListener('click',async()=>{const items=shoppingData();if(!items.length){alertToast('Liste vide');return}const message=items.map(i=>`${state.checked[i.key]?'☑':'☐'} ${i.name} — ${quantity(i.qty,i.unit)}`).join('\n');try{await navigator.clipboard.writeText(message);alertToast('Liste copiée')}catch(_){alertToast('Copie indisponible : sélectionne la liste à l’écran')}});$('#print').addEventListener('click',()=>window.print());renderFilters();renderCards();renderShopping();

// ── Planning de la semaine & menus types (repris de l'ancienne version Meal Planner Sport) ──
const DAYS=[['lundi','Lundi'],['mardi','Mardi'],['mercredi','Mercredi'],['jeudi','Jeudi'],['vendredi','Vendredi'],['samedi','Samedi'],['dimanche','Dimanche']];
const MEALS=[['pdj','P-déj'],['dejeuner','Déjeuner'],['collation','Collation'],['diner','Dîner'],['side','Side']];
// Correspondance des identifiants numériques de l'ancienne version (index = ancien id)
const OLD_IDS=[null,'curry-japonais','pates-poulet-chorizo','poulet-panko-curry','poulet-croute','chili-sin-carne','buddha-bowl','omelette-epinards','wok-tofu','salade-pates-poulet','saumon-patate-douce','porridge-myrtilles','smoothie-vert','lentilles-corail','pancakes-banane','maquereau-legumes','oeufs-avocat','steak-patate-douce','sardines-riz','banane-amandes','pomme-noix-chocolat','yaourt-banane','fromage-blanc-fruits'];
// Menus d'origine, par jour : [p-déj, déjeuner, collation, dîner] en anciens ids (0 = aucun)
const TEMPLATES={
  sport:{lundi:[11,5,19,7],mardi:[12,5,20,15],mercredi:[16,6,21,4],jeudi:[11,9,19,8],vendredi:[16,9,20,10],samedi:[14,17,22,13],dimanche:[0,17,21,18]},
  ultra:{lundi:[11,6,19,18],mardi:[16,2,21,13],mercredi:[12,5,19,10],jeudi:[11,9,22,7],vendredi:[16,3,20,15],samedi:[14,1,21,13],dimanche:[0,17,22,18]}
};
const TEMPLATE_NAMES={sport:'🏋️ Menu Sport',ultra:'⚡ Menu Ultra-Intense'};
const fromOldRow=row=>Object.fromEntries(MEALS.map(([m],i)=>[m,OLD_IDS[Array.isArray(row)?row[i]:row&&row[m]]||'']));
const normalizePlan=p=>Object.fromEntries(DAYS.map(([d])=>[d,Object.fromEntries(MEALS.map(([m])=>{const id=p&&p[d]&&p[d][m];return [m,typeof id==='string'&&resolve(id)?id:'']}))]));
const planCount=()=>DAYS.reduce((n,[d])=>n+MEALS.filter(([m])=>state.plan[d][m]).length,0);
// Portions par fournée : « portions »/« parts » = rendement, sinon rendement ÷ taille d'une portion (ex. 12 muffins ÷ 2)
const servings=r=>/^(portion|parts)/.test(r.unit)?r.yield:r.portion?r.yield/(parseFloat(r.portion)||1):r.yield;
function weekNeeds(){const counts={};for(const [d] of DAYS)for(const [m] of MEALS){const id=state.plan[d][m];if(id)counts[id]=(counts[id]||0)+1}return Object.entries(counts).map(([id,meals])=>{const v=resolve(id);return {v,meals,batches:Math.ceil(meals/servings(v.r))}}).sort((a,b)=>a.v.name.localeCompare(b.v.name,'fr'))}
function setWeekLabel(){const d=new Date(),mon=new Date(d);mon.setDate(d.getDate()-((d.getDay()+6)%7));const sun=new Date(mon);sun.setDate(mon.getDate()+6);const o={day:'numeric',month:'short'};$('#week-label').textContent=`Semaine du ${mon.toLocaleDateString('fr-FR',o)} au ${sun.toLocaleDateString('fr-FR',o)}`}
function mealOptions(sel){const cats=[...new Set(recipes.map(r=>r.category))];const opt=(key,label,icon)=>`<option value="${esc(key)}" ${key===sel?'selected':''}>${icon} ${esc(label)}</option>`;return `<option value="">— Aucun —</option>`+cats.map(c=>`<optgroup label="${esc(c)}">${recipes.filter(r=>r.category===c).map(r=>opt(r.id,r.name,r.icon)+(r.variants||[]).map(va=>{const v=resolve(r.id+'~'+va.key);return opt(v.key,v.name,r.icon)}).join('')).join('')}</optgroup>`).join('')}
function renderWeek(){const today=(new Date().getDay()+6)%7;$('#week').innerHTML=DAYS.map(([d,label],i)=>`<article class="day ${i===today?'today':''}"><div class="day-head"><h3>${label}</h3>${i===today?'<span class="today-badge">Aujourd’hui</span>':''}</div>${MEALS.map(([m,ml])=>`<div class="meal"><label for="meal-${d}-${m}">${ml}</label><select id="meal-${d}-${m}" data-day="${d}" data-meal="${m}">${mealOptions(state.plan[d][m])}</select></div>`).join('')}</article>`).join('');renderWeekSummary()}
function renderWeekSummary(){const needs=weekNeeds();const n=planCount();$('#week-summary').innerHTML=n?`<strong>${n} repas planifié${n>1?'s':''}</strong> · à cuisiner :<div class="needs">${needs.map(x=>`<span class="need">${x.v.icon} ${esc(x.v.name)} — ${x.batches} fournée${x.batches>1?'s':''} <em>(${x.meals} repas)</em></span>`).join('')}</div>`:'Aucun repas planifié pour l’instant.'}
// Récupère le planning de l'ancienne version (même site, même stockage navigateur) au premier passage
if(!state.plan){let old=null;try{old=JSON.parse(localStorage.getItem('mp_plan'))}catch(_){}state.plan=normalizePlan(old?Object.fromEntries(DAYS.map(([d])=>[d,fromOldRow(old[d])])):null);save();if(planCount())alertToast('Planning de l’ancienne version récupéré')}else state.plan=normalizePlan(state.plan);
$('#week').addEventListener('change',e=>{const s=e.target.closest('select[data-day]');if(!s)return;state.plan[s.dataset.day][s.dataset.meal]=s.value;save();renderWeekSummary()});
document.querySelector('.week-tools').addEventListener('click',e=>{const b=e.target.closest('[data-tpl]');if(!b)return;if(planCount()&&!confirm('Remplacer le planning actuel par ce menu ?'))return;state.plan=normalizePlan(Object.fromEntries(DAYS.map(([d])=>[d,fromOldRow(TEMPLATES[b.dataset.tpl][d])])));save();renderWeek();alertToast(`${TEMPLATE_NAMES[b.dataset.tpl]} chargé`)});
$('#clear-week').addEventListener('click',()=>{if(!planCount()||!confirm('Vider tout le planning de la semaine ?'))return;state.plan=normalizePlan(null);save();renderWeek()});
$('#week-to-list').addEventListener('click',()=>{const needs=weekNeeds();if(!needs.length){alertToast('Planifie au moins un repas');return}for(const {v,batches} of needs)state.selected[v.key]=Math.round(((Number(state.selected[v.key])||0)+batches)*100)/100;save();renderShopping();$('#courses').scrollIntoView({behavior:'smooth'});alertToast(`${needs.length} recette${needs.length>1?'s':''} ajoutée${needs.length>1?'s':''} à la liste`)});
$('#uncheck').addEventListener('click',()=>{if(!Object.keys(state.checked).length)return;state.checked={};save();renderShopping();alertToast('Tous les articles décochés')});
$('#foot-count').textContent=`${recipes.length} recettes · données sauvegardées localement`;
setWeekLabel();renderWeek();
