const $ = (s, root=document) => root.querySelector(s);
const state = {category:'Tout',query:'',selected:{},checked:{},active:null,scale:1};
try {
  const saved = JSON.parse(localStorage.getItem('cuisine-mouvement-v1'));
  if (saved && typeof saved === 'object') {
    state.selected = saved.selected && typeof saved.selected === 'object' ? saved.selected : {};
    state.checked = saved.checked && typeof saved.checked === 'object' ? saved.checked : {};
  }
} catch (_) {}
const save = () => { try { localStorage.setItem('cuisine-mouvement-v1',JSON.stringify({selected:state.selected,checked:state.checked})); } catch (_) {} };
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = n => new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(Math.round((n+Number.EPSILON)*10)/10);
const quantity = (n,u) => `${fmt(n)} ${u}`;
const norm = s => s.toLocaleLowerCase('fr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,"'").trim();
const unitKey = u => ({'pièces':'pièce','gousses':'gousse'}[u] || u);
const cleanCount = n => Math.min(30,Math.max(1,Math.round(Number(n)||1)));
function alertToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('visible');clearTimeout(alertToast.timer);alertToast.timer=setTimeout(()=>el.classList.remove('visible'),2300)}
function renderFilters(){const cats=['Tout',...new Set(recipes.map(r=>r.category))];$('#filters').innerHTML=cats.map(c=>`<button type="button" class="filter ${c===state.category?'active':''}" data-filter="${esc(c)}" aria-pressed="${c===state.category}">${esc(c)}</button>`).join('')}
function renderCards(){const q=norm(state.query);const found=recipes.filter(r=>(state.category==='Tout'||r.category===state.category)&&(!q||norm([r.name,r.category,...r.ingredients.map(i=>i[0])].join(' ')).includes(q)));$('#result-count').textContent=`${found.length} recette${found.length>1?'s':''}`;$('#cards').innerHTML=found.map(r=>`<article class="card"><div class="card-top"><span class="card-icon" aria-hidden="true">${r.icon}</span><span class="tag">${esc(r.category)}</span></div><h3>${esc(r.name)}</h3><p class="meta">${r.prep+r.cook} min · ${r.yield} ${esc(r.unit)}</p><button class="card-open" type="button" data-open="${r.id}"><span>Voir la recette</span><span aria-hidden="true">↗</span></button></article>`).join('')||'<p class="empty">Aucune recette trouvée.</p>'}
function renderDialog(){const r=recipes.find(x=>x.id===state.active);if(!r)return;const multiplier=state.scale/r.yield;$('#recipe-content').innerHTML=`<div class="dialog-icon" aria-hidden="true">${r.icon}</div><span class="eyebrow">${esc(r.category.toUpperCase())}</span><h2>${esc(r.name)}</h2><p class="dialog-meta">Préparation ${r.prep} min · Cuisson ${r.cook} min${r.temp?' · Four '+r.temp+' °C':''} · ${esc(r.tools)}</p><div class="scale"><span>Quantité</span><button data-scale="-1" type="button" aria-label="Réduire la quantité">−</button><strong>${state.scale}</strong><button data-scale="1" type="button" aria-label="Augmenter la quantité">+</button><span>${esc(r.unit)}${r.portion?' · collation : '+esc(r.portion):''}</span></div><h3>Ingrédients</h3><ul class="ingredients">${r.ingredients.map(([name,n,u])=>`<li><span>${esc(name)}</span><strong>${esc(quantity(n*multiplier,u))}</strong></li>`).join('')}</ul><h3>Préparation</h3><ol class="steps">${r.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p class="note"><strong>Conservation :</strong> ${esc(r.keep)}${r.note?'<br><strong>À savoir :</strong> '+esc(r.note):''}</p><button class="add" type="button" id="add-recipe">Ajouter les ingrédients à ma liste →</button>`}
function openRecipe(id){const r=recipes.find(x=>x.id===id);if(!r)return;state.active=id;state.scale=r.yield;renderDialog();$('#recipe-dialog').showModal()}
function shoppingData(){const map=new Map;for(const [id,batches] of Object.entries(state.selected)){const r=recipes.find(x=>x.id===id);if(!r||!Number.isFinite(+batches)||+batches<=0)continue;for(const [name,n,unit] of r.ingredients){const key=norm(name)+'|'+unitKey(unit);const cur=map.get(key);if(cur)cur.qty+=n*(+batches);else map.set(key,{key,name,qty:n*(+batches),unit:unitKey(unit)})}}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
function renderShopping(){const items=shoppingData();$('#cart-count').textContent=items.length;$('#shopping-status').textContent=items.length?`${items.filter(i=>!state.checked[i.key]).length} article(s) à acheter · ${items.length} au total`:'Aucun article';$('#shopping-list').innerHTML=items.map((it,i)=>`<div class="item ${state.checked[it.key]?'done':''}"><input type="checkbox" data-check="${i}" id="item-${i}" ${state.checked[it.key]?'checked':''}><label for="item-${i}">${esc(it.name)}</label><span class="item-qty">${esc(quantity(it.qty,it.unit))}</span></div>`).join('')||'<p class="empty">Ta liste est vide. Ouvre une recette puis ajoute ses ingrédients ici.</p>';const sel=Object.entries(state.selected).filter(([id,n])=>n>0&&recipes.some(r=>r.id===id));if(sel.length){$('#shopping-list').insertAdjacentHTML('beforeend',`<div class="selected"><h3>Recettes ajoutées</h3>${sel.map(([id,n])=>{const r=recipes.find(x=>x.id===id);return `<div class="selected-row"><span>${esc(r.name)} × ${n} fournée${n>1?'s':''}</span><button type="button" data-remove="${id}" aria-label="Retirer une fournée de ${esc(r.name)}">Retirer une fournée</button></div>`}).join('')}</div>`)}return items}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.category=b.dataset.filter;renderFilters();renderCards()});$('#search').addEventListener('input',e=>{state.query=e.target.value;renderCards()});$('#cards').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openRecipe(b.dataset.open)});$('#close-dialog').addEventListener('click',()=>$('#recipe-dialog').close());$('#recipe-dialog').addEventListener('click',e=>{if(e.target.id==='recipe-dialog')e.target.close();const scale=e.target.closest('[data-scale]');if(scale){state.scale=cleanCount(state.scale+Number(scale.dataset.scale));renderDialog()}if(e.target.id==='add-recipe'){const r=recipes.find(x=>x.id===state.active);state.selected[r.id]=(Number(state.selected[r.id])||0)+state.scale/r.yield;state.selected[r.id]=Math.round(state.selected[r.id]*100)/100;save();renderShopping();$('#recipe-dialog').close();alertToast('Ingrédients ajoutés à la liste')}});$('#shopping-list').addEventListener('change',e=>{if(!e.target.matches('[data-check]'))return;const it=shoppingData()[+e.target.dataset.check];if(!it)return;state.checked[it.key]=e.target.checked;save();renderShopping()});$('#shopping-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;state.selected[b.dataset.remove]=Math.max(0,Math.round((Number(state.selected[b.dataset.remove])-1)*100)/100);if(!state.selected[b.dataset.remove])delete state.selected[b.dataset.remove];save();renderShopping()});$('#clear').addEventListener('click',()=>{if(!Object.keys(state.selected).length)return;if(!confirm('Vider toute la liste de courses ?'))return;state.selected={};state.checked={};save();renderShopping()});$('#copy').addEventListener('click',async()=>{const items=shoppingData();if(!items.length){alertToast('Liste vide');return}const message=items.map(i=>`${state.checked[i.key]?'☑':'☐'} ${i.name} — ${quantity(i.qty,i.unit)}`).join('\n');try{await navigator.clipboard.writeText(message);alertToast('Liste copiée')}catch(_){alertToast('Copie indisponible : sélectionne la liste à l’écran')}});$('#print').addEventListener('click',()=>window.print());renderFilters();renderCards();renderShopping();
